pkg/dblog/resolver.go
pkg/source/pulsar.go

To support the replicated subscription feature of the pulsar geo-replication, the PR added the additional flag `PulsarReplicateState` for setting up the replicated subscriptions.
https://pulsar.apache.org/docs/2.10.x/administration-geo/#replicated-subscriptions

feat: introduce PulsarReplicateState to the PulsarConsumerSource

---

cmd/agent.go
pkg/sink/pulsar.go
pkg/source/postgres.go

So the pg2pulsar will not get stuck when not being able to read the latest message from the topic.

feature: ignore the timeout error when reading last messages in pulsar sink

---

pkg/source/pulsar.go

Since original implementation would skip first of after checkpoint message, and we only need after checkpoint message.

fix: fix ignore message problem

---

pkg/source/postgres.go
pkg/source/postgres_test.go

we know begin finalLSN = commit commitLSN and commit endLSN > commit commitLSN.
So, we can just send commitLSN in PG source and we can correctly compare LSN in Pulsar source

fix: should use commit lsn

---

pkg/cursor/pulsar.go

It seems like latestMessageID not always latest, It would have next message 🤔

fix: latestMessageID not always latest

---

Dockerfile
cmd/agent.go
cmd/configure.go
cmd/version.go
pkg/cursor/main.go
pkg/cursor/pulsar.go
pkg/cursor/pulsar_sub.go
pkg/sink/pulsar.go

The PR fixed the agent.pg2pulsar command related issues, including:
1. not forwarding the StartLSN/PulsarTracker params from the configure command
2. creating partitioned topics unexpectedly by the pulsarSubscriptionTracker 
As for the 2nd issue, the PR utilized the reader interface to ensure the existance **non-partitioned** topic (for passing the CDC events),
so the implementations added the additional steps to setup the reader before creating the producer/tracking-consumer.
The PR also adjusted the version command by adding more version info.

fix: fix the agent.pg2pulsar related issues

---

pkg/cursor/pulsar_sub.go
pkg/cursor/pulsar_sub_test.go

So we can access the subscription info from the pulsar-manager-ui panels.

feat: adjust the subscription name of the pulsar subscription cursor

---

cmd/agent.go

In previous implementations, the pulsarSub tracker type could cause significant backlog issues when the input rate of the associated topic is high. This occurs because the cursor is only updated every 10 minutes.
To address this issue, the PR introduces a new flag called `PulsarTrackerInterval`, which allows for adjusting the update interval. The PR also set the default value of the commit interval to be 1min.

feat: introduce PulsarTrackerInterval to the agent command

---

.circleci/config.yml
README.md
docker-compose.yml
hack/postgres/Dockerfile.11
hack/postgres/Dockerfile.12
hack/postgres/Dockerfile.13
hack/postgres/dockerbuild.sh
pkg/decode/schema.go
pkg/decode/schema_test.go
pkg/sink/postgres.go
pkg/sink/postgres_test.go
pkg/source/postgres.go
pkg/sql/builder.go
pkg/sql/builder_test.go
pkg/sql/source.go

The PR is for supporting the generated identity and the generated columns.
Since the `GENERATED ALWAYS AS (...)` is supported only for the pg12 or above,
the PR adjusted the related tests/configs to:
1. support testing against different pg versions (i.e. pg11, pg12, and pg13).
2. support running different tests against different versions (with the min pg version specified by the test case itself).
Also the new Dockerfile and the build script are introduced in the PR to support building different version of pg with pglogical.
to solve #27

feat: support generated columns

---

Dockerfile

The PR is for solving the compatibility issue after migrating to go 1.20.
To solve the issue, the PR added the `-extldflags=-static` flag when building the pgcapture binary.

fix: fix the glib compatibility related issue

---

example/client/main.go
pkg/pgcapture/consumer.go
pkg/pgcapture/consumer_test.go

The PR introduced the public function for setting the pgcapture consumer with the specific source other then the one implemented with the DBLogGateway.

feat: support consumser source other than DBLogGatewayConsumer

---

cmd/agent.go
cmd/configure.go
pkg/cursor/pulsar_sub.go
pkg/cursor/pulsar_sub_test.go

The PR added the support to setup the `SubscriptionReplicateState` of the consumer that helps maintain the cursor position of the pgcapture producer.

feat: add the support to set the replicate state for the subscription tracker consumer

---

Makefile
README.md
cmd/agent.go
cmd/agent_test.go
cmd/configure.go
cmd/controller.go
cmd/gateway.go
cmd/pg2pulsar.go
cmd/pulsar2pg.go
cmd/root.go
cmd/version.go
example/client/main.go
example/schedule/main.go
example/server/main.go
example/stop/main.go
main.go
pgcapture.go
pkg/dblog/gateway.go

Previously, developers need to import many different sub-packages and compose them to have a functional pgcapture consumer or gateway.
This PR is aimed to make this library to be more friendly to developers by aliasing commonly used objects to the `github.com/rueian/pgcapture`, not deeper sub-packages. So that developer's import list can be simplified like this:
To do so, this PR moves the `main` package from the root folder to the `cmd` folder.

chore: move common functions to the root

---

example/reset/main.go
go.mod
go.sum
internal/test/pg.go
pkg/cursor/pulsar_sub.go
pkg/dblog/control_test.go
pkg/dblog/dumper.go
pkg/dblog/dumper_test.go
pkg/dblog/gateway.go
pkg/dblog/gateway_test.go
pkg/dblog/resolver_test.go
pkg/dblog/scheduler_test.go
pkg/decode/pglogical.go
pkg/decode/pgoutput.go
pkg/sink/postgres.go
pkg/sink/postgres_test.go
pkg/source/postgres.go

I remove ioutil pkg and use errors pkg. Also, fix some comment typo.

refactor: remove deprecated pkg and fix typo

---

go.mod
go.sum
internal/cursormock/mock.go
internal/tool/main.go
pkg/cursor/pulsar.go
pkg/cursor/pulsar_sub.go
pkg/cursor/pulsar_sub_test.go
pkg/cursor/tracker.go
pkg/sink/pulsar.go
pkg/sink/pulsar_test.go

The PR is for solving the issue #45 .
In the previous implementations, the consumer of the subscription trackers would not actually consume the incoming messages. As a consequence, the message permits of the consumer would eventually been reduced to zero, and the broker would stop pushing messages to the consumer, which also meant that the consumer's replication snapshot cache would not be able to update to the latest version.
Upon acknowledging these messages, the broker encountered difficulty in locating the relevant replication snapshot within the outdated cache. As a result, the cursor was unable to replicate the latest position to the remote cluster(s).
To solve the issue, the PR added the additional go routine in the subscription tracker to drain the messages in the message queue. …

fix: solve the cursor not been replicated issue for the subscription tracker

---

cmd/agent.go
cmd/agent_test.go

In the previous implementation, `extract func` only extract string value. But client still can send different type in the params, we can not extract correct value.
Therefore, I modify `extract func` to return `map[string]*structpb.Value`.

feat: configure params support different type

---

pkg/source/postgres.go
pkg/sql/source.go

When pgSource restarts and cannot get the latest message id from Pulsar, possibly due to a timeout, starting replication with the XlogPos from IdentifySystem could lead to data loss. 
This is because the XlogPos represents the current database WAL flush location, not the confirmed flush LSN of the replication slot. Therefore, it could be greater than the begin and commit LSN. In this case, starting replication would not be able to replay the transactions between the confirmed flush LSN of the last replication slot and the XlogPos from IdentifySystem, resulting in data loss.
Therefore, if we cannot get the latest message from Pulsar, we should always start replaying from the confirmed flush LSN of the replication slot when restarting. Also, when the current LSN given to start replication …

fix: fix pg source restart loss tx problem

---

Dockerfile.build

forgot to add this `git config --global --add safe.directory /src` to solve go build error：
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```

fix: fix go build fail

---

pkg/cursor/main.go
pkg/source/postgres.go

The PR added the additional server time info to the checkpoints generated by the pg source,
so the application could use the timestamp info to check if it is continuously consuming the events (including the KeepAlive messages) from the pg source.
One of the usage of such the feature is to help setting up the readiness probe in the k8s deployment.

feat: add server time info to the pg source checkpoints

---

.gitignore
hack/postgres/extension/Makefile
hack/postgres/extension/expected/00_setup.out
hack/postgres/extension/expected/01_basic.out
hack/postgres/extension/expected/02_nested_ddl.out
hack/postgres/extension/expected/03_multi_query.out
hack/postgres/extension/pgcapture.c
hack/postgres/extension/pgcapture.h
hack/postgres/extension/sql/00_setup.sql
hack/postgres/extension/sql/01_basic.sql
hack/postgres/extension/sql/02_nested_ddl.sql
hack/postgres/extension/sql/03_multi_query.sql
hack/postgres/postgresql.conf

That function wasn't correctly handling multi-statement queries or CREATE EXTENSION commands that internally perform DDL.
I added first some minimal regression tests to show the current behavior with those corner cases and added the fix in the next commit.  Note that I didn't test those changes with pglogical.  I don't know much about this tool and I don't know if it can impact this approach.  If it does you can however ensure that pgcapture is executed first by changing the order of the modules in the needed *_preload_libraries parameter.
I also modifed the makefile to allow overloading the pg_config tool.  At least the RPM packagers rely on that so it would make their job easier if they want to package this tool.
I manually tested the changes on pg 12 to pg 16.  I didn't add a github …

Fix corner cases in pgcapture.current_query()

---

pkg/pgcapture/debounce.go

This PR addresses the issue of message loss in the debounce consumer handler by implementing a requeue behavior. The changes ensure that messages are not lost during the debounce process by requeuing them when necessary.

fix: fix loss message problem with debounce consumer handler with requeue behavior

---

hack/postgres/extension/Makefile
hack/postgres/extension/expected/04_temp.out
hack/postgres/extension/pg_import.c
hack/postgres/extension/pg_import.h
hack/postgres/extension/pgcapture.c
hack/postgres/extension/pgcapture.h
hack/postgres/extension/sql/04_temp.sql

Fixes #71
Temporary relations are not replicated, so we shouldn't report a query string for those.
This commit adds infrastructure to detect whether a given command is for a temporary relation or not, using the same internal function as upstream postgres, to guarantee that the detection will be identical.  The detection is not always easy as unqualified relation name depends on the search_path and various rules to detect what the final relation will be.  For instance, persistent view creation are automatically switched to temporary views if they reference temporary objects.
Finally, DROP commands are even trickier as they can reference both persistent and temporary relation.  It means that a new query has to be generated to ignore any temporary relation if any.
Some other DDL may need to …

feat: Ignore DDL query strings on temporary relations

---

pkg/dblog/dumper.go
pkg/dblog/dumper_test.go

This fixes the generated query in case any of the identifiers contains some double quote, which could be used to do an SQL injection.
The tests are updated to use a schema name that requires quoting and a relation name that requires escaping too.

Properly quote and escape identifiers in dumper query
