- pkg/sink/pulsar.go
So we can control the replicated clusters of the pulsar sink.
https://pulsar.apache.org/docs/2.9.x/administration-geo/#selective-replication
> feat(sink): add ReplicatedClusters

- pkg/cursor/main.go
- pkg/cursor/pulsar.go
- pkg/cursor/tracker.go
- pkg/dblog/gateway.go
- pkg/dblog/gateway_test.go
- pkg/pgcapture/consumer.go
- pkg/pgcapture/dblog.go
- pkg/pgcapture/debounce.go
- pkg/pgcapture/reflect.go
- pkg/sink/main.go
- pkg/sink/main_test.go
- pkg/sink/postgres.go
- pkg/sink/postgres_test.go
- pkg/sink/pulsar.go
- pkg/sink/pulsar_test.go
- pkg/source/main.go
- pkg/source/main_test.go
- pkg/source/postgres.go
- pkg/source/postgres_test.go
- pkg/source/pulsar.go
- pkg/source/pulsar_test.go
So we can easily refine the curosr related implementations.
> feat: introduce the cursor package

- pkg/source/postgres_test.go
fix https://github.com/rueian/pgcapture/pull/11 test problem.
> fix: fix test

- pkg/source/pulsar.go
Since we still cannot know the seq of redo done LSN.
> fix: should not compare seq

- cmd/agent.go
- cmd/agent_test.go
Fix the implementations of handling the optional params for the agent command.
> fix(cmd/agent): fix params handling for optional keys

- dockerbuild.sh
1. build image with version & latest tag
2. support build image in different platform
> feat: support build multi arch image

- pkg/pgcapture/consumer.go
- pkg/pgcapture/consumer_test.go
- pkg/pgcapture/reflect.go
Allows consumer to decode on fields that implement the `database/sql.Scanner` interface.
> Consumer support sql scanner

- cmd/agent.go
- cmd/root.go
- go.mod
The PR added the prom server to the agent command which helps exporting the prom metrics.
> feat: add the support to export the metrics on the agent cmd

- .circleci/config.yml
- Dockerfile
- Dockerfile.build
- Makefile
- docker-compose.yml
- dockerbuild.sh
- hack/postgres/11/Dockerfile
- hack/postgres/12/Dockerfile
- hack/postgres/13/Dockerfile
- hack/postgres/14/Dockerfile
- internal/test/env.go
- internal/test/pg.go
- internal/test/pulsar.go
- pkg/cursor/main_test.go
- pkg/cursor/pulsar_sub_test.go
- pkg/cursor/pulsar_test.go
- pkg/dblog/dumper_test.go
- pkg/decode/pglogical_test.go
- pkg/decode/pgoutput_test.go
- pkg/decode/schema_test.go
- pkg/sink/postgres_test.go
- pkg/sink/pulsar_test.go
- pkg/source/postgres_test.go
- pkg/source/pulsar_test.go
1. use env to inject test deps
2. setup test & clean script for local & ci
> feat: add dockerbuild.sh

- README.md
introduce decode plugin part and update dependencies part in documentation.
> docs: introduce decode plugin and dependencies

- pkg/pgcapture/consumer.go
- pkg/pgcapture/consumer_test.go
- pkg/pgcapture/json.go
- pkg/pgcapture/json_test.go
- pkg/pgcapture/reflect.go
Let consumer not only support pgtype v5 but also support golang builtin type.
> feat: consumer support pgtype v5

- README.md
> docs: update consumer part

- cmd/agent.go
> chore: mark batchTxSize as optional

- README.md
> docs: update docker-pgcapture link

- .circleci/config.yml
- docker-compose.yml
- hack/postgres/15/Dockerfile
- hack/postgres/15/pglogical/new/pglogical_output_plugin.c
- hack/postgres/15/pglogical/old/pglogical_output_plugin.c
- hack/postgres/15/pglogical/pglogical.patch
- hack/postgres/16/Dockerfile
- hack/postgres/16/pglogical/new/pglogical_output_plugin.c
- hack/postgres/16/pglogical/old/pglogical_output_plugin.c
- hack/postgres/16/pglogical/pglogical.patch
- hack/postgres/extension/pgcapture.c
> feat: support pg15 and pg16

- .github/workflows/go-binary-release.yml
> chore: auto build go binary after released

- README.md
> doc: use event queueing term

- pkg/source/postgres.go
In the previous PR #61, we intended to utilize the keepAlive messages from the replication protocol as the hearbeat to ensure the connection btw the source PG and the application.
Unfortunately, the keepAlive messages will not be send if the client constanly reports the LSN to the WAL sender (which is exactly what we do in the PGXSource).
To resolve the issue, we added the implementation to ask the WAL sender to reply the LSN reporting messages if needed (i.e. when not receiving the messages from the WAL sender with the specific period of time).
> feat:  add replyRequested when report LSN when needed

- docker-compose.yml
Should always test correct image for new behavior of extension
> chore: should test correct image

- pkg/source/pulsar.go
We need to add mutex lock to prevent data race
> fix: fix ack trackers data race

- dockerbuild.sh
> fix: replace docker-compose with docker compose

- .circleci/config.yml
- docker-compose.yml
- hack/postgres/17/Dockerfile
- hack/postgres/17/pglogical/new/pglogical_output_plugin.c
- hack/postgres/17/pglogical/old/pglogical_output_plugin.c
- hack/postgres/17/pglogical/pglogical.patch
> chore: support pg17

- pkg/dblog/dumper.go
The previous code was trying to generate all the possible ctid in a range of pages, which was a bit complex and could also lead to inefficient query execution in case of partial dump of a relation.
Postgres knows how to handle range predicates for tid datatype, and can even do direct physical access to the needed blocks starting with version 14, so let's rely on that to simplify the query and get free performance improvement in some cases.
> feat: Use ctid range predicate for the dumper query
